//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MESquare.Paparazzi.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int PAPARAZZI_TIMER_INTERVAL {
            get {
                return ((int)(this["PAPARAZZI_TIMER_INTERVAL"]));
            }
            set {
                this["PAPARAZZI_TIMER_INTERVAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Screenshots ")]
        public string PAPARAZZI_DESTINY_FOLDER {
            get {
                return ((string)(this["PAPARAZZI_DESTINY_FOLDER"]));
            }
            set {
                this["PAPARAZZI_DESTINY_FOLDER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Minutes")]
        public string PAPARAZZI_TIMER_INTERVAL_UNIT {
            get {
                return ((string)(this["PAPARAZZI_TIMER_INTERVAL_UNIT"]));
            }
            set {
                this["PAPARAZZI_TIMER_INTERVAL_UNIT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double PAPARAZZI_COUNTDOWN_INTERVAL {
            get {
                return ((double)(this["PAPARAZZI_COUNTDOWN_INTERVAL"]));
            }
            set {
                this["PAPARAZZI_COUNTDOWN_INTERVAL"] = value;
            }
        }
    }
}
